name: airbnb_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.7.0
  google_maps_flutter: ^2.9.0
  another_carousel_pro: ^1.0.2
  custom_info_window: ^1.0.1
  firebase_core: ^3.15.2
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.4.2
  google_sign_in: ^6.2.1
  provider: ^6.1.2
  intl: ^0.20.2
  flutter_localization: ^0.3.3
  image_picker: ^1.2.0
  firebase_storage: ^12.4.10
  url_launcher: ^6.3.2
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - asset/images/

